### ISSUE TITLE
requirements-check: Umbrella for next phase

### ISSUE THREAD

**Issue by johnSchnake** [vmware-tanzu/sonobuoy-plugins#85]
- [ ] Review 3 projects for checks required #82, #83, #84
- [ ] Document gaps in functionality and overlap from above
- [ ] Prioritize the above and make tickets for each feature

**Comment by johnSchnake** [comment]
Current similarities outstanding:
 [ ] need to AND/OR checks to produce flow control. May be best to let this be a use case for vendoring the library rather than using the plugin directly.

New functionality needed:
 - [ ] check if connected to internet
 - [ ] investigate and/or logic and how that _could_ be implemented in a plugin; this is generally at odds with have a simple schema config that you just fill out though. It would involve having to hand-write more complex checks which are formed from combining other checks.
 - [ ] Try POC for using this as a library to run and/or checks.

Questions to investigate:
 [ ] There was the idea that there were many more checks than this necessary as part of pre/post install. I need to re-review those pages and make sure I wasn't just looking at prereqs but also checks conducted during/after installation to ensure things were installed correctly.
